version: '3.8'

services:
  backend:
      image: backend
      environment:
        - REQUEST_ORIGIN=http://localhost:5000
        - REDIS_HOST=redis-host
      ports:
      - "8080:8080"
  frontend:
      image: frontend
      environment:
        - REACT_APP_BACKEND_URL=http://localhost:8080/
      ports:
      - "5000:5000"
  redis-host:
      image: redis
      ports:
      - "6379:6379"