version: '3.8'

services:
    text-log:
      image: devopsdockeruh/simple-web-service
      build: .
      volumes:
        - ./text.log:/usr/src/app/text.log
      container_name: devops
      command: bash -c "server"