version: "3.8"

services:
  backend:
    image: backend:latest
    ports:
      - 8080:8080
    environment:
      - REQUEST_ORIGIN=http://localhost:5000/
  frontend:
    image: frontend:latest
    ports:
      - 5000:5000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080/
